#!/bin/bash

echo "Dashboard"
minikube service kubernetes-dashboard --namespace kube-system --url
echo "Registry"
minikube service registry-ui --url
echo "Jenkins"
minikube service jenkins --namespace jenkins --url
echo "Holocene App"
minikube service holocene-service --url
echo "Rothstocks App"
minikube service rothstocks-service --url
