#!/bin/bash -e

KUBE_VERSION="v1.11.3"
#KUBE_VERSION="v1.12.0"
KUBE_MEMORY=12000
KUBE_CPUS=2
MINIKUBE_VERSION='v0.28.1'
#MINIKUBE_VERSION='v0.29.0'

function usage()
{
    echo "Recreate the kubernetes cluster using minikube"
    echo "NOTE: This will delete your existing kubernetes configuration"
    echo ""
    echo "./recreate_kube.sh"
    echo "\t-h --help"
    echo ""
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
#        --environment)
#            ENVIRONMENT=$VALUE
#            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo ""
while true; do
    read -e -p "Do you wish to to stop and delete minikube and install jenkins minikube? [yN] " yn
    case ${yn:0:1} in
        y|Y )
            break
        ;;
        * )
            exit
        ;;
    esac
done

#minikube stop
#minikube delete
sudo cp -f ~/.minikube/cache/iso/minikube-${MINIKUBE_VERSION}.iso .
sudo rm -rf ~/.minikube
sudo mkdir -p ~/.minikube/cache/iso/
sudo cp minikube-${MINIKUBE_VERSION}.iso ~/.minikube/cache/iso/
sudo chmod 600 ~/.minikube/cache/iso/minikube-${MINIKUBE_VERSION}.iso
sudo rm -rf ~/.kube

# Start Kubernetes using minikube and add useful items
minikube start --memory ${KUBE_MEMORY} --cpus ${KUBE_CPUS} --kubernetes-version ${KUBE_VERSION}

minikube addons enable ingress
