#!/bin/bash -e

KUBE_VERSION="v1.11.1"
#KUBE_VERSION="v1.11.1-beta.0"
#KUBE_VERSION="v1.10.5"
KUBE_MEMORY=4000
KUBE_CPUS=2

function usage()
{
    echo "Recreate the kubernetes cluster using minikube"
    echo "NOTE: This will delete your existing kubernetes configuration"
    echo ""
    echo "./recreate_kube.sh"
    echo "\t-h --help"
    echo ""
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
#        --environment)
#            ENVIRONMENT=$VALUE
#            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo ""
while true; do
    read -e -p "Do you wish to to stop and delete minikube and install jenkins minikube? [yN] " yn
    case ${yn:0:1} in
        y|Y )
            break
        ;;
        * )
            exit
        ;;
    esac
done

minikube stop
minikube delete
sudo rm -rf ~/.minikube
sudo rm -rf ~/.kube

# Start Kubernetes using minikube and add useful items
minikube start --memory ${KUBE_MEMORY} --cpus ${KUBE_CPUS} --kubernetes-version ${KUBE_VERSION}
#exit

#minikube addons enable heapster
minikube addons enable ingress
