#!/bin/bash -e

function usage()
{
    echo "Adds a registry and Jenkins to kubernetes cluster"
    echo ""
    echo "./start_kube.sh"
    echo "\t-h --help"
    echo "\t--openall"
    echo ""
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
#        --environment)
#            ENVIRONMENT=$VALUE
#            ;;
        --openall)
            OPEN_ALL=1
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo ""
while true; do
    read -e -p "Do you wish install a registry and Jenkins? [yN] " yn
    case ${yn:0:1} in
        y|Y )
            break
        ;;
        * )
            exit
        ;;
    esac
done

# Helm
#
helm init

kubectl rollout status deployments/tiller-deploy --namespace kube-system

#./start_monitoring

./start_registry

./start_jenkins

#./start_services
