#!/bin/bash -e

function usage()
{
    echo "Adds a registry and Jenkins to kubernetes cluster"
    echo ""
    echo "./start_kube.sh"
    echo "\t-h --help"
    echo "\t--openall"
    echo ""
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
#        --environment)
#            ENVIRONMENT=$VALUE
#            ;;
        --openall)
            OPEN_ALL=1
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo ""
while true; do
    read -e -p "Do you wish install a registry and Jenkins? [yN] " yn
    case ${yn:0:1} in
        y|Y )
            break
        ;;
        * )
            exit
        ;;
    esac
done

# Helm
#
helm init

kubectl rollout status deployments/tiller-deploy --namespace kube-system

helm install stable/prometheus --name prometheus
helm install stable/grafana --name grafana

# Setup registry
kubectl apply -f registry/registry.yml
kubectl rollout status deployments/registry

# Wait for registry to finish initializing
until kubectl get pod $(kubectl get pods -l 'app=registry' -o jsonpath='{.items[0].metadata.name}') -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' | grep True ; do
    sleep 15
done

# Setup proxy to registry
./registry/setup_reg_proxy

# These are necessary for jenkins to deploy the hello-kenzan app.
kubectl create sa jenkins
kubectl create clusterrolebinding jenkins --clusterrole cluster-admin --serviceaccount=jenkins:default

# Build jenkins and push to registry
cd jenkins
./build_jenkins.sh

# Wait for registry to finish with jenkins
sleep 30

# Add newly built jenkins to cluster
kubectl apply -f jenkins.yml
kubectl rollout status deployments/jenkins --namespace jenkins

# Wait for jenkins to initialize
if [ "$OPEN_ALL" != "" ] ; then
sleep 5
echo "Monitoring-grafana"
minikube service monitoring-grafana --namespace kube-system --url
sleep 5
echo "Registry"
minikube service registry-ui --url
fi
sleep 5
echo "Dashboard"
minikube service kubernetes-dashboard --namespace kube-system --url
sleep 5
echo "Jenkins"
minikube service jenkins --namespace jenkins --url

