#!/bin/bash


minikube service kubernetes-dashboard --namespace kube-system --url
minikube service registry-ui --url
minikube service jenkins --namespace jenkins --url
minikube service monitoring-grafana --namespace kube-system --url
