#!/bin/bash


minikube service kubernetes-dashboard --namespace kube-system
minikube service registry-ui
minikube service jenkins --namespace jenkins
#minikube service monitoring-grafana --namespace kube-system --url
