#!/bin/bash -e

function usage()
{
    echo "Adds a registry and Jenkins to kubernetes cluster"
    echo ""
    echo "./start_kube.sh"
    echo "\t-h --help"
    echo "\t--openall"
    echo ""
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
#        --environment)
#            ENVIRONMENT=$VALUE
#            ;;
        --openall)
            OPEN_ALL=1
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

echo ""
while true; do
    read -e -p "Do you wish install a registry and Jenkins? [yN] " yn
    case ${yn:0:1} in
        y|Y )
            break
        ;;
        * )
            exit
        ;;
    esac
done

# Helm
#
helm init

kubectl rollout status deployments/tiller-deploy --namespace kube-system

kubectl apply -f monitoring-namespace.yaml

helm install stable/prometheus --name prometheus --namespace monitoring
helm install stable/grafana --name grafana --namespace monitoring

# Wait for registry to finish initializing
until kubectl get pod $(kubectl get pods --namespace monitoring -l 'app=grafana' -o jsonpath='{.items[0].metadata.name}') -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' | grep True ; do
    echo -n "."
    sleep 15
done

./start_registry

./start_jenkins

# Wait for jenkins to initialize
if [ "$OPEN_ALL" != "" ] ; then
sleep 5
echo "Grafana"
minikube service grafana --namespace monitoring --url
sleep 5
echo "Registry"
minikube service registry-ui --url
fi
sleep 5
echo "Dashboard"
minikube service kubernetes-dashboard --namespace kube-system --url
sleep 5
echo "Jenkins"
minikube service jenkins --namespace jenkins --url

