#!/bin/bash -e

RAILS_KEY=`cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 128 | head -n 1`
RAILS_KEY_TEST=`cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 128 | head -n 1`

MARIADB_IMAGE="docker.io/bitnami/mariadb:10.1.33"

function usage()
{
    echo "if this was a real script you would see something useful here"
    echo ""
    echo "./simple_args_parsing.sh"
    echo "\t-h --help"
    echo "\t--openall"
    echo ""
}

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
#        --environment)
#            ENVIRONMENT=$VALUE
#            ;;
        --openall)
            OPEN_ALL=1
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

randomstring () {
  COUNT=${1:-10}
  random_string=`date +%s | sha256sum | base64 | head -c $COUNT`
}

randomstring 10
root_pass=$random_string

echo ""
echo "Please enter or accept the following passwords"
echo ""
read -e -p "MySQL root password? [<random 10 chars>] " password
if [ ! -z "$password" ] ; then
  root_pass=$password
fi

#randomstring 10
redis_user_pass=$random_string
read -e -p "Redis_user password? [<random 10 chars>] " password
if [ ! -z "$password" ] ; then
  redis_user_pass=$password
fi

#randomstring 10
test_redis_user_pass=$random_string
read -e -p "Test Redis_user password? [<random 10 chars>] " password
if [ ! -z "$password" ] ; then
  test_redis_user_pass=$password
fi

echo ""
while true; do
    read -e -p "Do you wish to install helm and install mariadb and phpmyadmin? [yN] " yn
    case ${yn:0:1} in
        y|Y )
            break
        ;;
        * )
            exit
        ;;
    esac
done

# Keep the keys to the kingdom
echo "root_pass=\"${root_pass}\""       > .kdr_env
echo "redis_user_pass=\"${redis_user_pass}\"" >> .kdr_env
echo "test_redis_user_pass=\"${test_redis_user_pass}\"" >> .kdr_env

# Add namespaces
kubectl apply --namespace app-test -f db-apps-namespace.yaml
kubectl apply --namespace app-test -f app-test-namespace.yaml

./start_mariadb

./start_redis

# Secrets must be in each environment to be useful
#
set +e
for namespace in default db-apps app-test ; do
    kubectl create secret generic db-root-pass --namespace ${namespace} --from-literal=password=${root_pass}
    if [ "${namespace}" == "app-test" ] ; then
	kubectl create secret generic redis-test --namespace ${namespace} --from-literal=redis_password=${test_redis_user_pass}
    else
	kubectl create secret generic redis --namespace ${namespace} --from-literal=password=${redis_user_password}
    fi
done

kubectl rollout status statefulset/mariadb-mariadb-master --namespace db-apps

set -e

