#!/bin/bash


minikube service kubernetes-dashboard --namespace kube-system
minikube service registry-ui
minikube service jenkins --namespace jenkins
minikube service hello-kenzan --namespace jenkins
minikube service grafana --namespace monitoring

