#!/bin/bash
#
# Setup registry
kubectl apply -f registry/registry.yaml
#kubectl rollout status deployments/registry

# Wait for registry to finish initializing
until kubectl get pod $(kubectl get pods -l 'app=registry' -n default -o jsonpath='{.items[0].metadata.name}') -n default -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' | grep True ; do
    echo -n "."
    sleep 15
done

# Setup proxy to registry
./registry/setup_reg_proxy

